kind = "mobile"
previewPath = "/"
title = "Rota Manager"
version = "1.0.0"
id = "artifacts/rota-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 23944

[services.development]
run = "pnpm --filter @workspace/rota-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/rota-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/rota-mobile", "run", "serve" ]

[services.env]
PORT = "23944"
BASE_PATH = "/"
